import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Feed from "./components/Feed";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main ">
        {/* Header */}
        <Header />

        <div className="bg-green-50 h-screen  grid grid-cols-3 px-8 pt-4">
          {/* Feed */}
          <div className=" col-span-2">
            <Feed className="" />
          </div>

          {/* Sidebar */}
          <div className="col-span-1">
            <Sidebar className="" />
          </div>
        </div>
      </div>
    </div>
  );
}
